///
/// File generated by cpct_aks2c CPCtelera script
/// Souce file of this conversion: music/death.aks
/// Generation time: vie 30 oct 2020 21:42:50 CET
///

/// Song 'song_death' metadata macros
#define song_death_address  0x4202
#define song_death_size     103
#define song_death_end      0x4268

/// Song 'song_death' array declaration
extern void song_death[song_death_size];
