///
/// File generated by cpct_aks2c CPCtelera script
/// Souce file of this conversion: music/title.aks
/// Generation time: vie 30 oct 2020 21:42:50 CET
///

/// Song 'song_menu' metadata macros
#define song_menu_address  0x4000
#define song_menu_size     259
#define song_menu_end      0x4102

/// Song 'song_menu' array declaration
extern void song_menu[song_menu_size];
