///
/// File generated by cpct_aks2c CPCtelera script
/// Souce file of this conversion: music/victory.aks
/// Generation time: vie 30 oct 2020 20:51:21 CET
///

/// Song 'song_victory' metadata macros
#define song_victory_address  0x4103
#define song_victory_size     255
#define song_victory_end      0x4201

/// Song 'song_victory' array declaration
extern void song_victory[song_victory_size];
